//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhoneNumberControl {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PhoneNumberControl.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area Code.
        /// </summary>
        internal static string AREA_CODE {
            get {
                return ResourceManager.GetString("AREA_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        internal static string COUNTRY {
            get {
                return ResourceManager.GetString("COUNTRY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afghanistan	af	+93
        ///Albania	al	+355
        ///Algeria	dz	+213
        ///American Samoa	as	+684
        ///Andorra	ad	+376
        ///Angola	ao	+244
        ///Anguilla	ai	+1-264
        ///Antarctica	aq	+672
        ///Antigua and Barbuda	ag	+1-268
        ///Argentina	ar	+54
        ///Armenia	am	+374
        ///Aruba	aw	+297
        ///Australia	au	+61
        ///Austria	at	+43
        ///Azerbaijan	az	+994
        ///Bahamas	bs	+1-242
        ///Bahrain	bh	+973
        ///Bangladesh	bd	+880
        ///Barbados	bb	+1-246
        ///Belarus	by	+375
        ///Belgium	be	+32
        ///Belize	bz	+501
        ///Benin	bj	+229
        ///Bermuda	bm	+1-441
        ///Bhutan	bt	+975
        ///Bolivia	bo	+591
        ///Bosnia-Herzegovina	ba	+387
        ///Botswa [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CountryDetails {
            get {
                return ResourceManager.GetString("CountryDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5.
        /// </summary>
        internal static string MIN_PHONE_LENGTH {
            get {
                return ResourceManager.GetString("MIN_PHONE_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Code.
        /// </summary>
        internal static string PHONE_CODE {
            get {
                return ResourceManager.GetString("PHONE_CODE", resourceCulture);
            }
        }
    }
}
